title:            Alice Goldfuss
description:      
# put your disqus here
disqus_shortname: 
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:              # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://blog.alicegoldfuss.com
#url: 

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Posts'
    url: '/posts'
  - title: 'Talks'
    url: '/talks'
  - title: 'Publications'
    url: '/publications'
  - title: 'Shirts'
    url: 'https://interruptdesigns.threadless.com/'
  - title: 'About'
    url: '/about'
  - title: 'Contact'
    url: '/contact'
  - title: 'RSS'
    url: '/feed.xml'
 # - title: 'Tags'
  #  url: '/tags'
  #- title: 'Categories'
   # url: '/categories'
    #type: 'categories'

# Owner/author information
owner:
  name:           Alice Goldfuss
  site:           http://alicegoldfuss.com
  avatar:         images/smokeyeye-lg.png
  bio: |+
       Alice Goldfuss is a systems punk currently helping GitHub run their cutting-edge container platform. She loves kernel crashes, memory design, and performance hacks. :rainbow: :floppy_disk: :octocat:
       <br>
       <br>
       Alice has consulted on some books (<i>Docker: Up & Running</i>, <i>Effective DevOps</i>, <i>Site Reliability Engineering vol 2</i>), presented at some conferences (SREcon, Velocity, Container Summit), and run some others (LISA17, DevOps Days Portland). You can follow her on Twitter :bird: <a href="http://twitter.com/alicegoldfuss" target="_blank">(@alicegoldfuss)</a>, but you’ll probably regret it.
  email:          you@email.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: alicegoldfuss # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  #github: alicegoldfuss

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
#social:
#  - title: "github"
#    url: "https://github.com/aron-bordin"
#  - title: "linkedin"
#    url: "https://br.linkedin.com/in/aronbordin"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-83860617-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["exampleposts", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate, jemoji]
